spring:
  application:
    name: api-gateway
server:
  port: 80
#    方案1直接url映射
#zuul:
#  routes:
#    personprovider1:
#      path: /personprovider1/**
#      url: http://localhost:8088/
#    personprovider2:
#      path: /personprovider2/**
#      url: http://localhost:9099/


#      方案2通过在Eureka服务注册的serviceId进行映射
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
zuul:
  routes:
    personprovider:
      path: /service/**
      service-id: PERSONPROVIDER
  retryable: true

ribbon:
  ConnectionTimeOut: 1000
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 5
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000

